name: Python Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout File
      - uses: actions/checkout@v2
      - run: python hello.py
    
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Build Artifact
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: hello
          path: .
